version: '3.8'

services:
  todo_list_db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - todo_list_db:/var/lib/postgresql/data

volumes:
  todo_list_db:
    driver: local